import type{FastifyPluginAsync}from'fastify';
const error={type:'object',required:['error'],properties:{error:{type:'object',required:['code','message','requestId'],properties:{code:{type:'string'},message:{type:'string'},requestId:{type:'string'},details:{type:'object'}}}}};
const routes:FastifyPluginAsync=async f=>{f.get('/openapi.json',async()=>({openapi:'3.1.0',info:{title:'Turf GDS B2B API',version:'1.0.0',description:'Backend APIs for Venue Owners, Booking Partners, inventory distribution and financial close.'},servers:[{url:'/api/v1'}],security:[],components:{securitySchemes:{ownerBearer:{type:'http',scheme:'bearer'},partnerPortalBearer:{type:'http',scheme:'bearer'},adminBearer:{type:'http',scheme:'bearer'},partnerHmac:{type:'apiKey',in:'header',name:'X-Api-Key',description:'Also sign timestamp, method, path, raw-body SHA-256 and X-Request-Id using X-Signature. Send X-Timestamp and a unique X-Request-Id.'}},schemas:{Error:error}},paths:{
 '/availability':{get:{summary:'Search contract-authorized availability',security:[{partnerHmac:[]}],responses:{'200':{description:'Available courts and intervals'}}}},
 '/bookings/holds':{post:{summary:'Create a short-lived inventory hold',security:[{partnerHmac:[]}],responses:{'201':{description:'Hold created'},'409':{description:'Inventory conflict'}}}},
 '/bookings/confirm':{post:{summary:'Confirm held inventory',description:'Requires Idempotency-Key.',security:[{partnerHmac:[]}],responses:{'201':{description:'Booking confirmed'}}}},
 '/bookings/{bookingId}/cancel':{post:{summary:'Cancel using the immutable Venue policy snapshot',security:[{partnerHmac:[]}],responses:{'200':{description:'Cancellation outcome'},'409':{description:'Cancellation not permitted'}}}},
 '/partners/me/settlements/{settlementId}/remittance':{get:{summary:'Get Partner remittance status and instructions',security:[{partnerHmac:[]}],responses:{'200':{description:'Remittance'}}},post:{summary:'Create idempotent remittance instructions',security:[{partnerHmac:[]}],responses:{'201':{description:'Remittance instructions'}}}},
 '/inventory-connectors/reference/{connectorId}/events':{post:{summary:'Reference PMS inventory webhook',description:'Sign the raw body using X-Connector-Signature.',responses:{'200':{description:'Applied, ignored or conflict'}}}},
 '/provider-webhooks/razorpay':{post:{summary:'Razorpay remittance and payout webhook',description:'Raw body signature is verified using X-Razorpay-Signature.',responses:{'200':{description:'Idempotently processed'}}}},
 '/admin/inventory-conflicts':{get:{summary:'List inventory synchronization conflicts',security:[{adminBearer:[]}],responses:{'200':{description:'Conflicts'}}}},
 '/admin/verifications/{verificationId}/preliminary-review':{post:{summary:'OPS/Admin KYC maker review',security:[{adminBearer:[]}],responses:{'204':{description:'Review recorded'}}}}
}}));};export default routes;
