import { createHmac, timingSafeEqual } from 'node:crypto';
import { AppError } from '../../shared/errors/app-error.js';
export interface RazorpayProviderConfig{enabled:boolean;keyId?:string;keySecret?:string;webhookSecret?:string;accountNumber?:string;baseUrl:string;}
export interface TreasuryProvider{createCollectionReference(v:{reference:string;amountMinor:number;description:string;closeAt:Date}):Promise<{id:string;accountNumber:string|null;ifsc:string|null}>;createPayout(v:{idempotencyKey:string;fundAccountId:string;amountMinor:number;reference:string}):Promise<{id:string;status:string}>;verifyWebhook(body:Buffer,signature:string):void;}
export function createRazorpayProvider(config:RazorpayProviderConfig):TreasuryProvider{return{
 async createCollectionReference(v){if(!config.enabled)return{id:`va_sandbox_${v.reference}`,accountNumber:`9999${v.reference.replace(/\D/g,'').slice(-12).padStart(12,'0')}`,ifsc:'RAZR0000001'};const body={receivers:{types:['bank_account']},description:v.description,amount_expected:v.amountMinor,close_by:Math.floor(v.closeAt.getTime()/1000),notes:{settlement_reference:v.reference}};const response=await call(config,'/v1/virtual_accounts',body);const receiver=Array.isArray(response.receivers)?response.receivers.find((x:unknown)=>(x as {entity?:string}).entity==='bank_account') as {account_number?:string;ifsc?:string}|undefined:undefined;return{id:String(response.id),accountNumber:receiver?.account_number??null,ifsc:receiver?.ifsc??null};},
 async createPayout(v){if(!config.enabled)return{id:`pout_sandbox_${v.reference}`,status:'processing'};if(!config.accountNumber)throw unavailable('RAZORPAY_ACCOUNT_NUMBER is required for payouts');const response=await call(config,'/v1/payouts',{account_number:config.accountNumber,fund_account_id:v.fundAccountId,amount:v.amountMinor,currency:'INR',mode:'NEFT',purpose:'payout',queue_if_low_balance:true,reference_id:v.reference},{'X-Payout-Idempotency':v.idempotencyKey});return{id:String(response.id),status:String(response.status)};},
 verifyWebhook(body,signature){if(!config.webhookSecret)throw unavailable('Razorpay webhook secret is not configured');const expected=createHmac('sha256',config.webhookSecret).update(body).digest('hex');const a=Buffer.from(signature),b=Buffer.from(expected);if(a.length!==b.length||!timingSafeEqual(a,b))throw new AppError({code:'INVALID_PROVIDER_SIGNATURE',message:'Provider webhook signature is invalid',statusCode:401});}
};}
async function call(config:RazorpayProviderConfig,path:string,body:unknown,headers:Record<string,string>={}){if(!config.keyId||!config.keySecret)throw unavailable('Razorpay API credentials are not configured');const response=await fetch(`${config.baseUrl}${path}`,{method:'POST',headers:{authorization:`Basic ${Buffer.from(`${config.keyId}:${config.keySecret}`).toString('base64')}`,'content-type':'application/json',...headers},body:JSON.stringify(body),signal:AbortSignal.timeout(15_000)});const value=await response.json().catch(()=>({})) as Record<string,unknown>;if(!response.ok)throw new AppError({code:'TREASURY_PROVIDER_ERROR',message:'Razorpay request failed',statusCode:502,details:{providerStatus:response.status,providerError:value.error??null}});return value;}
function unavailable(message:string){return new AppError({code:'TREASURY_PROVIDER_NOT_CONFIGURED',message,statusCode:503});}
