import { createHash } from 'node:crypto';
import { ObjectId, type ClientSession } from 'mongodb';
import type { DatabaseConnection } from '../../../shared/database/database-connection.js';
import { AppError } from '../../../shared/errors/app-error.js';
import type { OutboxRepository } from '../../../shared/communications/outbox.repository.js';
import type { OwnerAccessService } from '../../identity/owner/owner-access.service.js';
import type { VenueOnboardingAgreementDocument } from './onboarding-agreement.types.js';

export type ProposeAgreementInput={adminId:string;venueId:string;ownerId:string;templateId?:string;title:string;termsText?:string;platformCommissionBps:number;settlementCycle:'T_PLUS_N'|'WEEKLY'|'MONTHLY';settlementLagDays:number;cancellationPolicy:{cancellationAllowed:boolean;defaultRefundBps:number;noShowRefundBps:number;ownerCancellationNoticeMinutes:number;refundRules:Array<{minMinutesBeforeStart:number;refundBps:number}>};correlationId:string};
export interface OnboardingAgreementService{propose(input:ProposeAgreementInput):Promise<object>;createTemplate(input:{adminId:string;code:string;title:string;termsText:string}):Promise<object>;listTemplates():Promise<object[]>;getOwner(input:{actorOwnerId:string;venueId:string}):Promise<object>;accept(input:{actorOwnerId:string;venueId:string;version:number;acceptanceIp:string;acceptanceUserAgent?:string|undefined;correlationId:string}):Promise<object>;requestChanges(input:{actorOwnerId:string;venueId:string;version:number;note:string;correlationId:string}):Promise<object>;isAccepted(ownerId:string,venueId:string,session?:ClientSession):Promise<boolean>}

export function createOnboardingAgreementService(input:{database:DatabaseConnection;ownerAccessService:OwnerAccessService;outboxRepository:OutboxRepository;now?:()=>Date}):OnboardingAgreementService{
 const now=input.now??(()=>new Date());const agreements=()=>input.database.db.collection<VenueOnboardingAgreementDocument>('venue_onboarding_agreements');const templates=()=>input.database.db.collection<{_id:ObjectId;code:string;title:string;terms_text:string;version:number;status:'ACTIVE'|'SUPERSEDED';created_by:ObjectId;created_at:Date;updated_at:Date}>('contract_templates');
 return{
  async createTemplate(v){const timestamp=now(),code=required(v.code).toUpperCase(),latest=await templates().find({code}).sort({version:-1}).limit(1).next();const value={_id:new ObjectId(),code,title:required(v.title),terms_text:required(v.termsText),version:(latest?.version??0)+1,status:'ACTIVE' as const,created_by:oid(v.adminId),created_at:timestamp,updated_at:timestamp};await input.database.withTransaction(async({session})=>{await templates().updateMany({code,status:'ACTIVE'},{$set:{status:'SUPERSEDED',updated_at:timestamp}},{session});await templates().insertOne(value,{session});});return templateView(value);},
  async listTemplates(){return(await templates().find({status:'ACTIVE'}).sort({code:1}).toArray()).map(templateView);},
  async propose(v){validate(v);const template=v.templateId?await templates().findOne({_id:oid(v.templateId),status:'ACTIVE'}):null;if(v.templateId&&!template)throw new AppError({code:'CONTRACT_TEMPLATE_NOT_FOUND',message:'Active contract template was not found',statusCode:404});const termsText=template?.terms_text??required(v.termsText),timestamp=now();let result!:VenueOnboardingAgreementDocument;await input.database.withTransaction(async({session})=>{const venueId=oid(v.venueId),latest=await agreements().find({venue_id:venueId},{session}).sort({version:-1}).limit(1).next();if(latest?.status==='PROPOSED')await agreements().updateOne({_id:latest._id},{$set:{status:'SUPERSEDED',updated_at:timestamp}},{session});result={_id:new ObjectId(),venue_id:venueId,owner_id:oid(v.ownerId),title:required(v.title),terms_text:termsText,template_id:template?._id??null,template_version:template?.version??null,terms_hash:hash(termsText),platform_commission_bps:v.platformCommissionBps,settlement_cycle:v.settlementCycle,settlement_lag_days:v.settlementLagDays,cancellation_policy:{cancellation_allowed:v.cancellationPolicy.cancellationAllowed,default_refund_bps:v.cancellationPolicy.defaultRefundBps,no_show_refund_bps:v.cancellationPolicy.noShowRefundBps,owner_cancellation_notice_minutes:v.cancellationPolicy.ownerCancellationNoticeMinutes,refund_rules:v.cancellationPolicy.refundRules.map(x=>({min_minutes_before_start:x.minMinutesBeforeStart,refund_bps:x.refundBps})).sort((a,b)=>b.min_minutes_before_start-a.min_minutes_before_start)},status:'PROPOSED',version:(latest?.version??0)+1,proposed_by:oid(v.adminId),proposed_at:timestamp,accepted_by:null,accepted_at:null,acceptance_ip:null,acceptance_user_agent:null,audit_history:[{event_type:latest?.status==='ACCEPTED'?'ONBOARDING_AGREEMENT_AMENDMENT_PROPOSED':'ONBOARDING_AGREEMENT_PROPOSED',actor_type:'ADMIN',actor_id:oid(v.adminId),correlation_id:v.correlationId,terms_hash:hash(termsText),occurred_at:timestamp}],created_at:timestamp,updated_at:timestamp};await agreements().insertOne(result,{session});await enqueue(input.outboxRepository,result,'CONTRACT_PROPOSED',v.correlationId,timestamp,session);});return present(result);},
  async getOwner(v){await input.ownerAccessService.requireVenueMembership(v.actorOwnerId,v.venueId);const value=await agreements().find({venue_id:oid(v.venueId),owner_id:oid(v.actorOwnerId),status:{$in:['PROPOSED','CHANGES_REQUESTED','ACCEPTED']}}).sort({version:-1}).limit(1).next();if(!value)throw new AppError({code:'ONBOARDING_AGREEMENT_NOT_FOUND',message:'No onboarding agreement has been proposed',statusCode:404});return present(value);},
  async accept(v){await input.ownerAccessService.requirePermission(v.actorOwnerId,v.venueId,'MANAGE_VENUE');const timestamp=now();let value:VenueOnboardingAgreementDocument|null=null;await input.database.withTransaction(async({session})=>{value=await agreements().findOneAndUpdate({venue_id:oid(v.venueId),owner_id:oid(v.actorOwnerId),status:'PROPOSED',version:v.version},{$set:{status:'ACCEPTED',accepted_by:oid(v.actorOwnerId),accepted_at:timestamp,acceptance_ip:v.acceptanceIp,acceptance_user_agent:v.acceptanceUserAgent?.slice(0,500)??null,updated_at:timestamp},$push:{audit_history:{$each:[{event_type:'ONBOARDING_AGREEMENT_ACCEPTED',actor_type:'VENUE_OWNER',actor_id:oid(v.actorOwnerId),correlation_id:v.correlationId,terms_hash:null,occurred_at:timestamp}],$slice:-100}}},{returnDocument:'after',session});if(!value)throw new AppError({code:'ONBOARDING_AGREEMENT_VERSION_CONFLICT',message:'The proposed agreement was not found or changed',statusCode:409});await agreements().updateMany({venue_id:value.venue_id,status:'ACCEPTED',_id:{$ne:value._id}},{$set:{status:'SUPERSEDED',updated_at:timestamp}},{session});await enqueue(input.outboxRepository,value,'CONTRACT_ACCEPTED',v.correlationId,timestamp,session);});return present(value!);},
  async requestChanges(v){await input.ownerAccessService.requirePermission(v.actorOwnerId,v.venueId,'MANAGE_VENUE');const timestamp=now(),value=await agreements().findOneAndUpdate({venue_id:oid(v.venueId),owner_id:oid(v.actorOwnerId),status:'PROPOSED',version:v.version},{$set:{status:'CHANGES_REQUESTED',updated_at:timestamp},$push:{audit_history:{$each:[{event_type:'ONBOARDING_AGREEMENT_CHANGES_REQUESTED',actor_type:'VENUE_OWNER',actor_id:oid(v.actorOwnerId),correlation_id:v.correlationId,note:required(v.note),occurred_at:timestamp}],$slice:-100}}},{returnDocument:'after'});if(!value)throw new AppError({code:'ONBOARDING_AGREEMENT_VERSION_CONFLICT',message:'The proposed agreement was not found or changed',statusCode:409});return present(value);},
  async isAccepted(ownerId,venueId,session){return Boolean(await agreements().findOne({owner_id:oid(ownerId),venue_id:oid(venueId),status:'ACCEPTED'},{...(session?{session}:{}),projection:{_id:1}}));}
 };
}
async function enqueue(outbox:OutboxRepository,value:VenueOnboardingAgreementDocument,eventType:'CONTRACT_PROPOSED'|'CONTRACT_ACCEPTED',correlationId:string,now:Date,session:ClientSession){await outbox.enqueue({aggregateType:'CONTRACT',aggregateId:value._id,partnerId:null,venueId:value.venue_id,environment:'PRODUCTION',eventType,eventVersion:value.version,correlationId,payload:{agreementId:value._id.toHexString(),venueId:value.venue_id.toHexString(),status:value.status,version:value.version,termsHash:value.terms_hash},now,session});}
function present(v:VenueOnboardingAgreementDocument){return{agreementId:v._id.toHexString(),venueId:v.venue_id.toHexString(),ownerId:v.owner_id.toHexString(),templateId:v.template_id?.toHexString()??null,templateVersion:v.template_version,title:v.title,termsText:v.terms_text,termsHash:v.terms_hash,platformCommissionBps:v.platform_commission_bps,settlementCycle:v.settlement_cycle,settlementLagDays:v.settlement_lag_days,cancellationPolicy:{cancellationAllowed:v.cancellation_policy.cancellation_allowed,defaultRefundBps:v.cancellation_policy.default_refund_bps,noShowRefundBps:v.cancellation_policy.no_show_refund_bps,ownerCancellationNoticeMinutes:v.cancellation_policy.owner_cancellation_notice_minutes,refundRules:v.cancellation_policy.refund_rules.map(r=>({minMinutesBeforeStart:r.min_minutes_before_start,refundBps:r.refund_bps}))},status:v.status,version:v.version,proposedAt:v.proposed_at.toISOString(),acceptedAt:v.accepted_at?.toISOString()??null};}function templateView(v:{_id:ObjectId;code:string;title:string;terms_text:string;version:number;status:string}){return{templateId:v._id.toHexString(),code:v.code,title:v.title,termsText:v.terms_text,version:v.version,status:v.status,termsHash:hash(v.terms_text)};}
function validate(v:ProposeAgreementInput){for(const n of[v.platformCommissionBps,v.cancellationPolicy.defaultRefundBps,v.cancellationPolicy.noShowRefundBps,...v.cancellationPolicy.refundRules.map(r=>r.refundBps)])if(!Number.isInteger(n)||n<0||n>10000)throw new AppError({code:'INVALID_AGREEMENT_BPS',message:'Agreement percentages must be integers from 0 to 10000 basis points',statusCode:400});if(!Number.isInteger(v.settlementLagDays)||v.settlementLagDays<0||!Number.isInteger(v.cancellationPolicy.ownerCancellationNoticeMinutes)||v.cancellationPolicy.ownerCancellationNoticeMinutes<0)throw new AppError({code:'INVALID_AGREEMENT_TERMS',message:'Agreement timing values are invalid',statusCode:400});}
function hash(v:string){return createHash('sha256').update(v,'utf8').digest('hex');}function oid(v:string){if(!ObjectId.isValid(v))throw new AppError({code:'INVALID_ID',message:'Identifier is invalid',statusCode:400});return new ObjectId(v);}function required(v:string|undefined){const x=v?.trim();if(!x)throw new AppError({code:'FIELD_REQUIRED',message:'Agreement title and text are required',statusCode:400});return x;}
