import type { Db, Document } from 'mongodb';

async function ensure(db:Db,name:string,validator:Document){const exists=await db.listCollections({name},{nameOnly:true}).hasNext();if(!exists)await db.createCollection(name,{validator,validationLevel:'strict',validationAction:'error'});else await db.command({collMod:name,validator,validationLevel:'strict',validationAction:'error'});}
const oid={bsonType:'objectId'};const date={bsonType:'date'};const nullableDate={bsonType:['date','null']};const nullableString={bsonType:['string','null']};
export async function initializeInventorySyncPersistence(db:Db):Promise<void>{
  await ensure(db,'inventory_connectors',{$jsonSchema:{bsonType:'object',additionalProperties:false,required:['_id','venue_id','environment','provider','name','status','webhook_secret_hash','last_sync_at','last_cursor','created_by','created_at','updated_at'],properties:{_id:oid,venue_id:oid,environment:{enum:['SANDBOX','PRODUCTION']},provider:{enum:['REFERENCE']},name:{bsonType:'string'},status:{enum:['ACTIVE','DISABLED']},webhook_secret_hash:{bsonType:'string'},last_sync_at:nullableDate,last_cursor:nullableString,created_by:oid,created_at:date,updated_at:date}}});
  await ensure(db,'external_resource_mappings',{$jsonSchema:{bsonType:'object',additionalProperties:false,required:['_id','connector_id','venue_id','resource_type','internal_id','external_id','created_at','updated_at'],properties:{_id:oid,connector_id:oid,venue_id:oid,resource_type:{enum:['COURT']},internal_id:oid,external_id:{bsonType:'string'},created_at:date,updated_at:date}}});
  await ensure(db,'inventory_sync_runs',{$jsonSchema:{bsonType:'object',additionalProperties:false,required:['_id','connector_id','direction','status','cursor_before','cursor_after','processed_count','conflict_count','error','started_at','completed_at'],properties:{_id:oid,connector_id:oid,direction:{enum:['PULL','PUSH','WEBHOOK']},status:{enum:['RUNNING','COMPLETED','FAILED']},cursor_before:nullableString,cursor_after:nullableString,processed_count:{bsonType:'int',minimum:0},conflict_count:{bsonType:'int',minimum:0},error:nullableString,started_at:date,completed_at:nullableDate}}});
  await ensure(db,'inventory_conflicts',{$jsonSchema:{bsonType:'object',additionalProperties:false,required:['_id','connector_id','venue_id','court_id','external_event_id','type','status','details','resolved_by','resolved_at','resolution_note','created_at'],properties:{_id:oid,connector_id:oid,venue_id:oid,court_id:{bsonType:['objectId','null']},external_event_id:{bsonType:'string'},type:{enum:['UNMAPPED_RESOURCE','OVERLAPPING_CONFIRMED_BOOKING','STALE_UPDATE','INVALID_EVENT']},status:{enum:['OPEN','RESOLVED','IGNORED']},details:{bsonType:'object'},resolved_by:{bsonType:['objectId','null']},resolved_at:nullableDate,resolution_note:nullableString,created_at:date}}});
  await ensure(db,'external_inventory_events',{$jsonSchema:{bsonType:'object',additionalProperties:false,required:['_id','connector_id','external_event_id','external_version','event_type','external_court_id','starts_at','ends_at','external_booking_reference','status','received_at'],properties:{_id:oid,connector_id:oid,external_event_id:{bsonType:'string'},external_version:{bsonType:'int',minimum:1},event_type:{enum:['AVAILABILITY_BLOCKED','AVAILABILITY_RELEASED','BOOKING_CONFIRMED','BOOKING_CANCELLED']},external_court_id:{bsonType:'string'},starts_at:date,ends_at:date,external_booking_reference:nullableString,status:{enum:['APPLIED','CONFLICT','IGNORED']},received_at:date}}});
  await db.collection('inventory_connectors').createIndex({venue_id:1,environment:1,provider:1},{unique:true,name:'uq_inventory_connector_venue_provider'});
  await db.collection('external_resource_mappings').createIndex({connector_id:1,resource_type:1,external_id:1},{unique:true,name:'uq_external_resource_mapping'});
  await db.collection('external_resource_mappings').createIndex({connector_id:1,resource_type:1,internal_id:1},{unique:true,name:'uq_internal_resource_mapping'});
  await db.collection('external_inventory_events').createIndex({connector_id:1,external_event_id:1},{unique:true,name:'uq_external_inventory_event'});
  await db.collection('inventory_conflicts').createIndex({connector_id:1,status:1,created_at:-1},{name:'ix_inventory_conflicts_open'});
  await db.collection('inventory_sync_runs').createIndex({connector_id:1,started_at:-1},{name:'ix_inventory_sync_runs'});
}
