import { createHash, createHmac, timingSafeEqual } from 'node:crypto';
import { ObjectId } from 'mongodb';
import type { DatabaseConnection } from '../../shared/database/database-connection.js';
import { AppError } from '../../shared/errors/app-error.js';
import type { ExternalInventoryEventDocument, ExternalResourceMappingDocument, InventoryConflictDocument, InventoryConnectorDocument, InventorySyncRunDocument, SyncEnvironment } from './inventory-sync.types.js';
import type { SlotDocument } from '../venue/inventory/inventory.types.js';

type ExternalEvent={eventId:string;version:number;type:ExternalInventoryEventDocument['event_type'];externalCourtId:string;startsAt:string;endsAt:string;externalBookingReference?:string};
export interface InventorySyncService{
 createConnector(v:{venueId:string;environment:SyncEnvironment;name:string;adminId:string}):Promise<object>;
 listConnectors(v:{venueId?:string;environment?:SyncEnvironment}):Promise<object[]>;
 mapCourt(v:{connectorId:string;courtId:string;externalCourtId:string}):Promise<object>;
 receiveReferenceEvent(v:{connectorId:string;signature:string;rawBody:Buffer;event:ExternalEvent}):Promise<object>;
 pullReferenceInventory(v:{connectorId:string;token:string;updatedAfter?:string;limit?:number}):Promise<object>;
 listRuns(connectorId:string):Promise<object[]>;listConflicts(v:{connectorId?:string;status?:'OPEN'|'RESOLVED'|'IGNORED'}):Promise<object[]>;
 resolveConflict(v:{conflictId:string;adminId:string;resolution:'RESOLVED'|'IGNORED';note:string}):Promise<object>;
 setStatus(v:{connectorId:string;status:'ACTIVE'|'DISABLED'}):Promise<object>;
}
export function createInventorySyncService(database:DatabaseConnection,masterSecret:string,now:()=>Date=()=>new Date()):InventorySyncService{
 const connectors=()=>database.db.collection<InventoryConnectorDocument>('inventory_connectors');const mappings=()=>database.db.collection<ExternalResourceMappingDocument>('external_resource_mappings');const runs=()=>database.db.collection<InventorySyncRunDocument>('inventory_sync_runs');const conflicts=()=>database.db.collection<InventoryConflictDocument>('inventory_conflicts');const events=()=>database.db.collection<ExternalInventoryEventDocument>('external_inventory_events');
 const secret=(id:ObjectId)=>createHmac('sha256',masterSecret).update(`inventory-connector:${id.toHexString()}`).digest('base64url');
 return{
  async createConnector(v){const timestamp=now(),id=new ObjectId();const venueId=oid(v.venueId),adminId=oid(v.adminId);if(!await database.db.collection('venues').findOne({_id:venueId},{projection:{_id:1}}))throw notFound('VENUE_NOT_FOUND','Venue was not found');const raw=secret(id);const doc:InventoryConnectorDocument={_id:id,venue_id:venueId,environment:v.environment,provider:'REFERENCE',name:req(v.name),status:'ACTIVE',webhook_secret_hash:sha(raw),last_sync_at:null,last_cursor:null,created_by:adminId,created_at:timestamp,updated_at:timestamp};try{await connectors().insertOne(doc);}catch(error){if((error as {code?:number}).code===11000)throw new AppError({code:'INVENTORY_CONNECTOR_EXISTS',message:'A connector already exists for this venue and environment',statusCode:409});throw error;}return{...viewConnector(doc),webhookSecret:raw};},
  async listConnectors(v){const filter:Record<string,unknown>={};if(v.venueId)filter.venue_id=oid(v.venueId);if(v.environment)filter.environment=v.environment;return(await connectors().find(filter).sort({created_at:-1}).toArray()).map(viewConnector);},
  async mapCourt(v){const connector=await connectors().findOne({_id:oid(v.connectorId)});if(!connector)throw notFound('INVENTORY_CONNECTOR_NOT_FOUND','Inventory connector was not found');const courtId=oid(v.courtId);if(!await database.db.collection('courts').findOne({_id:courtId,venue_id:connector.venue_id},{projection:{_id:1}}))throw notFound('COURT_NOT_FOUND','Court was not found for this connector venue');const timestamp=now();const value:ExternalResourceMappingDocument={_id:new ObjectId(),connector_id:connector._id,venue_id:connector.venue_id,resource_type:'COURT',internal_id:courtId,external_id:req(v.externalCourtId),created_at:timestamp,updated_at:timestamp};await mappings().updateOne({connector_id:connector._id,resource_type:'COURT',external_id:value.external_id},{$set:{internal_id:courtId,venue_id:connector.venue_id,updated_at:timestamp},$setOnInsert:{_id:value._id,created_at:timestamp}},{upsert:true});return{mappingId:value._id.toHexString(),connectorId:v.connectorId,courtId:v.courtId,externalCourtId:value.external_id};},
  async receiveReferenceEvent(v){const connector=await connectors().findOne({_id:oid(v.connectorId),status:'ACTIVE'});if(!connector)throw notFound('INVENTORY_CONNECTOR_NOT_FOUND','Active inventory connector was not found');verify(v.signature,v.rawBody,secret(connector._id));const existing=await events().findOne({connector_id:connector._id,external_event_id:v.event.eventId});if(existing)return{eventId:existing.external_event_id,status:existing.status,replayed:true};const startsAt=new Date(v.event.startsAt),endsAt=new Date(v.event.endsAt);if(!Number.isInteger(v.event.version)||v.event.version<1||Number.isNaN(startsAt.getTime())||Number.isNaN(endsAt.getTime())||startsAt>=endsAt)throw new AppError({code:'INVALID_INVENTORY_EVENT',message:'External inventory event is invalid',statusCode:400});const mapping=await mappings().findOne({connector_id:connector._id,resource_type:'COURT',external_id:v.event.externalCourtId});const timestamp=now(),runId=new ObjectId();let status:ExternalInventoryEventDocument['status']='APPLIED',conflictCount=0;
   await database.withTransaction(async({session})=>{await runs().insertOne({_id:runId,connector_id:connector._id,direction:'WEBHOOK',status:'RUNNING',cursor_before:connector.last_cursor,cursor_after:String(v.event.version),processed_count:0,conflict_count:0,error:null,started_at:timestamp,completed_at:null},{session});if(!mapping){status='CONFLICT';conflictCount=1;await conflicts().insertOne(makeConflict(connector,null,v.event,'UNMAPPED_RESOURCE',timestamp),{session});}else{const overlap=await database.db.collection<SlotDocument>('slots').findOne({court_id:mapping.internal_id,environment:connector.environment,starts_at:{$lt:endsAt},ends_at:{$gt:startsAt},status:{$in:['BOOKED','HELD']}},{session});if(overlap&&v.event.type!=='BOOKING_CANCELLED'){status='CONFLICT';conflictCount=1;await conflicts().insertOne(makeConflict(connector,mapping.internal_id,v.event,'OVERLAPPING_CONFIRMED_BOOKING',timestamp,{slotId:overlap._id.toHexString(),slotStatus:overlap.status}),{session});}else await applyEvent(database,connector,mapping,v.event,startsAt,endsAt,timestamp,session);}
    await events().insertOne({_id:new ObjectId(),connector_id:connector._id,external_event_id:req(v.event.eventId),external_version:v.event.version,event_type:v.event.type,external_court_id:req(v.event.externalCourtId),starts_at:startsAt,ends_at:endsAt,external_booking_reference:v.event.externalBookingReference?.trim()||null,status,received_at:timestamp},{session});await runs().updateOne({_id:runId},{$set:{status:'COMPLETED',cursor_after:String(v.event.version),processed_count:1,conflict_count:conflictCount,completed_at:timestamp}},{session});await connectors().updateOne({_id:connector._id},{$set:{last_sync_at:timestamp,last_cursor:String(v.event.version),updated_at:timestamp}},{session});});return{eventId:v.event.eventId,status,replayed:false};},
  async pullReferenceInventory(v){const connector=await connectors().findOne({_id:oid(v.connectorId),status:'ACTIVE'});if(!connector||sha(v.token)!==connector.webhook_secret_hash)throw new AppError({code:'INVALID_CONNECTOR_AUTHENTICATION',message:'Connector authentication failed',statusCode:401});const updatedAfter=v.updatedAfter?new Date(v.updatedAfter):new Date(0);if(Number.isNaN(updatedAfter.getTime()))throw new AppError({code:'INVALID_SYNC_CURSOR',message:'updatedAfter must be a valid timestamp',statusCode:400});const limit=Math.min(Math.max(v.limit??100,1),500),courtMaps=await mappings().find({connector_id:connector._id,resource_type:'COURT'}).toArray(),byCourt=new Map(courtMaps.map(m=>[m.internal_id.toHexString(),m.external_id]));const values=await database.db.collection<SlotDocument>('slots').find({venue_id:connector.venue_id,environment:connector.environment,court_id:{$in:courtMaps.map(m=>m.internal_id)},updated_at:{$gt:updatedAfter}}).sort({updated_at:1,_id:1}).limit(limit).toArray();const next=values.at(-1)?.updated_at??updatedAfter;return{connectorId:v.connectorId,environment:connector.environment,items:values.map(slot=>({slotId:slot._id.toHexString(),externalCourtId:byCourt.get(slot.court_id.toHexString()),bookingType:slot.booking_type,startsAt:slot.starts_at.toISOString(),endsAt:slot.ends_at.toISOString(),status:slot.status,priceMinor:slot.price_minor,currency:slot.currency,version:slot.version,updatedAt:slot.updated_at.toISOString()})),nextCursor:next.toISOString(),hasMore:values.length===limit};},
  async listRuns(id){return(await runs().find({connector_id:oid(id)}).sort({started_at:-1}).limit(100).toArray()).map(v=>({runId:v._id.toHexString(),connectorId:v.connector_id.toHexString(),direction:v.direction,status:v.status,processedCount:v.processed_count,conflictCount:v.conflict_count,error:v.error,startedAt:v.started_at.toISOString(),completedAt:v.completed_at?.toISOString()??null}));},
  async listConflicts(v){const filter:Record<string,unknown>={};if(v.connectorId)filter.connector_id=oid(v.connectorId);if(v.status)filter.status=v.status;return(await conflicts().find(filter).sort({created_at:-1}).limit(200).toArray()).map(viewConflict);},
  async resolveConflict(v){const value=await conflicts().findOneAndUpdate({_id:oid(v.conflictId),status:'OPEN'},{$set:{status:v.resolution,resolved_by:oid(v.adminId),resolved_at:now(),resolution_note:req(v.note)}},{returnDocument:'after'});if(!value)throw notFound('INVENTORY_CONFLICT_NOT_FOUND','Open inventory conflict was not found');return viewConflict(value);},
  async setStatus(v){const value=await connectors().findOneAndUpdate({_id:oid(v.connectorId)},{$set:{status:v.status,updated_at:now()}},{returnDocument:'after'});if(!value)throw notFound('INVENTORY_CONNECTOR_NOT_FOUND','Inventory connector was not found');return viewConnector(value);}
 };
}
async function applyEvent(database:DatabaseConnection,c:InventoryConnectorDocument,m:ExternalResourceMappingDocument,e:ExternalEvent,startsAt:Date,endsAt:Date,timestamp:Date,session:import('mongodb').ClientSession){const slots=database.db.collection<SlotDocument>('slots');if(e.type==='AVAILABILITY_RELEASED'||e.type==='BOOKING_CANCELLED'){await slots.deleteMany({court_id:m.internal_id,environment:c.environment,starts_at:startsAt,ends_at:endsAt,source:'EXTERNAL_CONNECTOR' as never,status:{$in:['BLOCKED','UNAVAILABLE']}},{session});return;}const status=e.type==='BOOKING_CONFIRMED'?'UNAVAILABLE':'BLOCKED';const existing=await slots.findOne({court_id:m.internal_id,environment:c.environment,booking_type:'OPEN_TIME',starts_at:startsAt,ends_at:endsAt},{session});if(existing){await slots.updateOne({_id:existing._id,status:{$nin:['BOOKED','HELD']}},{$set:{status,updated_at:timestamp},$inc:{version:1},$push:{audit_history:{$each:[{event_type:'EXTERNAL_INVENTORY_APPLIED',actor_type:'SYSTEM',actor_id:null,previous_status:existing.status,new_status:status,reason:`Connector event ${e.eventId}`,correlation_id:e.eventId,occurred_at:timestamp}],$slice:-100}}},{session});return;}await slots.insertOne({_id:new ObjectId(),court_id:m.internal_id,venue_id:c.venue_id,environment:c.environment,booking_type:'OPEN_TIME',starts_at:startsAt,ends_at:endsAt,price_minor:null,currency:'INR',status,hold_id:null,hold_partner_id:null,hold_expires_at:null,hold_created_at:null,source:'EXTERNAL_CONNECTOR' as never,booking_id:null,audit_history:[{event_type:'EXTERNAL_INVENTORY_APPLIED',actor_type:'SYSTEM',actor_id:null,previous_status:null,new_status:status,reason:`Connector event ${e.eventId}`,correlation_id:e.eventId,occurred_at:timestamp}],version:1,created_at:timestamp,updated_at:timestamp},{session});}
function makeConflict(c:InventoryConnectorDocument,courtId:ObjectId|null,e:ExternalEvent,type:InventoryConflictDocument['type'],now:Date,extra:Record<string,unknown>={}):InventoryConflictDocument{return{_id:new ObjectId(),connector_id:c._id,venue_id:c.venue_id,court_id:courtId,external_event_id:e.eventId,type,status:'OPEN',details:{externalCourtId:e.externalCourtId,startsAt:e.startsAt,endsAt:e.endsAt,...extra},resolved_by:null,resolved_at:null,resolution_note:null,created_at:now};}
function viewConnector(v:InventoryConnectorDocument){return{connectorId:v._id.toHexString(),venueId:v.venue_id.toHexString(),environment:v.environment,provider:v.provider,name:v.name,status:v.status,lastSyncAt:v.last_sync_at?.toISOString()??null,lastCursor:v.last_cursor,createdAt:v.created_at.toISOString()};}function viewConflict(v:InventoryConflictDocument){return{conflictId:v._id.toHexString(),connectorId:v.connector_id.toHexString(),venueId:v.venue_id.toHexString(),courtId:v.court_id?.toHexString()??null,externalEventId:v.external_event_id,type:v.type,status:v.status,details:v.details,resolvedAt:v.resolved_at?.toISOString()??null,resolutionNote:v.resolution_note,createdAt:v.created_at.toISOString()};}
function verify(value:string,body:Buffer,secret:string){const supplied=value.startsWith('sha256=')?value.slice(7):value;const expected=createHmac('sha256',secret).update(body).digest('hex');const a=Buffer.from(supplied),b=Buffer.from(expected);if(a.length!==b.length||!timingSafeEqual(a,b))throw new AppError({code:'INVALID_CONNECTOR_SIGNATURE',message:'Connector signature is invalid',statusCode:401});}function sha(v:string){return createHash('sha256').update(v).digest('base64url');}function oid(v:string){if(!ObjectId.isValid(v))throw new AppError({code:'INVALID_ID',message:'Identifier is invalid',statusCode:400});return new ObjectId(v);}function req(v:string){const x=v?.trim();if(!x)throw new AppError({code:'FIELD_REQUIRED',message:'A required field is empty',statusCode:400});return x;}function notFound(code:string,message:string){return new AppError({code,message,statusCode:404});}
