import type { FastifyPluginAsync } from 'fastify';
import type { AdminAuthService } from '../identity/platform/auth.service.js';
import type { OwnerAccessService } from '../identity/owner/owner-access.service.js';
import { createAdminAuthenticationHook, createOwnerAuthenticationHook, requireAdminRole, requireOwnerContext } from '../identity/shared/auth-context.js';
import type { InventorySyncService } from './inventory-sync.service.js';

const id={type:'string',pattern:'^[a-fA-F0-9]{24}$'} as const;
const connectorParams={type:'object',additionalProperties:false,required:['connectorId'],properties:{connectorId:id}} as const;
const routes:FastifyPluginAsync<{service:InventorySyncService;adminAuthService:AdminAuthService;ownerAccessService:OwnerAccessService}>=async(fastify,o)=>{
 const admin=createAdminAuthenticationHook(o.adminAuthService),owner=createOwnerAuthenticationHook(o.ownerAccessService);
 fastify.post<{Body:{venueId:string;environment:'SANDBOX'|'PRODUCTION';name:string}}>('/admin/inventory-connectors',{preHandler:admin,schema:{body:{type:'object',additionalProperties:false,required:['venueId','environment','name'],properties:{venueId:id,environment:{enum:['SANDBOX','PRODUCTION']},name:{type:'string',minLength:2,maxLength:120}}}}},async(r,reply)=>reply.status(201).send(await o.service.createConnector({...r.body,adminId:requireAdminRole(r).adminId})));
 fastify.get<{Querystring:{venueId?:string;environment?:'SANDBOX'|'PRODUCTION'}}>('/admin/inventory-connectors',{preHandler:admin,schema:{querystring:{type:'object',additionalProperties:false,properties:{venueId:id,environment:{enum:['SANDBOX','PRODUCTION']}}}}},async r=>{requireAdminRole(r);return o.service.listConnectors(r.query);});
 fastify.post<{Params:{connectorId:string};Body:{courtId:string;externalCourtId:string}}>('/admin/inventory-connectors/:connectorId/mappings',{preHandler:admin,schema:{params:connectorParams,body:{type:'object',additionalProperties:false,required:['courtId','externalCourtId'],properties:{courtId:id,externalCourtId:{type:'string',minLength:1,maxLength:200}}}}},async(r,reply)=>{requireAdminRole(r);return reply.status(201).send(await o.service.mapCourt({connectorId:r.params.connectorId,...r.body}));});
 fastify.get<{Params:{connectorId:string}}>('/admin/inventory-connectors/:connectorId/runs',{preHandler:admin,schema:{params:connectorParams}},async r=>{requireAdminRole(r);return o.service.listRuns(r.params.connectorId);});
 fastify.patch<{Params:{connectorId:string};Body:{status:'ACTIVE'|'DISABLED'}}>('/admin/inventory-connectors/:connectorId/status',{preHandler:admin,schema:{params:connectorParams,body:{type:'object',additionalProperties:false,required:['status'],properties:{status:{enum:['ACTIVE','DISABLED']}}}}},async r=>{requireAdminRole(r);return o.service.setStatus({connectorId:r.params.connectorId,status:r.body.status});});
 fastify.get<{Querystring:{connectorId?:string;status?:'OPEN'|'RESOLVED'|'IGNORED'}}>('/admin/inventory-conflicts',{preHandler:admin,schema:{querystring:{type:'object',additionalProperties:false,properties:{connectorId:id,status:{enum:['OPEN','RESOLVED','IGNORED']}}}}},async r=>{requireAdminRole(r);return o.service.listConflicts(r.query);});
 fastify.post<{Params:{conflictId:string};Body:{resolution:'RESOLVED'|'IGNORED';note:string}}>('/admin/inventory-conflicts/:conflictId/resolve',{preHandler:admin,schema:{params:{type:'object',additionalProperties:false,required:['conflictId'],properties:{conflictId:id}},body:{type:'object',additionalProperties:false,required:['resolution','note'],properties:{resolution:{enum:['RESOLVED','IGNORED']},note:{type:'string',minLength:1,maxLength:1000}}}}},async r=>o.service.resolveConflict({conflictId:r.params.conflictId,adminId:requireAdminRole(r).adminId,...r.body}));
 fastify.get<{Params:{venueId:string}}>('/owner/venues/:venueId/inventory-connectors',{preHandler:owner,schema:{params:{type:'object',additionalProperties:false,required:['venueId'],properties:{venueId:id}}}},async r=>{const actor=requireOwnerContext(r);await o.ownerAccessService.requireVenueMembership(actor.ownerId,r.params.venueId);return o.service.listConnectors({venueId:r.params.venueId});});
 fastify.post<{Params:{connectorId:string};Body:{eventId:string;version:number;type:'AVAILABILITY_BLOCKED'|'AVAILABILITY_RELEASED'|'BOOKING_CONFIRMED'|'BOOKING_CANCELLED';externalCourtId:string;startsAt:string;endsAt:string;externalBookingReference?:string}}>('/inventory-connectors/reference/:connectorId/events',{config:{rawBody:true},schema:{params:connectorParams,body:{type:'object',additionalProperties:false,required:['eventId','version','type','externalCourtId','startsAt','endsAt'],properties:{eventId:{type:'string',minLength:1,maxLength:200},version:{type:'integer',minimum:1},type:{enum:['AVAILABILITY_BLOCKED','AVAILABILITY_RELEASED','BOOKING_CONFIRMED','BOOKING_CANCELLED']},externalCourtId:{type:'string',minLength:1,maxLength:200},startsAt:{type:'string',format:'date-time'},endsAt:{type:'string',format:'date-time'},externalBookingReference:{type:'string',minLength:1,maxLength:200}}}}},async(r,reply)=>{const signature=r.headers['x-connector-signature'];if(typeof signature!=='string')return reply.status(401).send({error:{code:'CONNECTOR_SIGNATURE_REQUIRED',message:'x-connector-signature is required',requestId:r.id}});return o.service.receiveReferenceEvent({connectorId:r.params.connectorId,signature,rawBody:Buffer.isBuffer(r.rawBody)?r.rawBody:Buffer.from(JSON.stringify(r.body)),event:r.body});});
 fastify.get<{Params:{connectorId:string};Querystring:{updatedAfter?:string;limit?:number}}>('/inventory-connectors/reference/:connectorId/inventory',{schema:{params:connectorParams,querystring:{type:'object',additionalProperties:false,properties:{updatedAfter:{type:'string',format:'date-time'},limit:{type:'integer',minimum:1,maximum:500}}}}},async(r,reply)=>{const token=r.headers['x-connector-token'];if(typeof token!=='string')return reply.status(401).send({error:{code:'CONNECTOR_TOKEN_REQUIRED',message:'x-connector-token is required',requestId:r.id}});return o.service.pullReferenceInventory({connectorId:r.params.connectorId,token,...r.query});});
};
export default routes;
