import type { FastifyPluginAsync } from 'fastify';
import { createAdminAuthenticationHook,createPartnerPortalAuthenticationHook,requireAdminRole,requirePartnerPortalContext } from '../shared/auth-context.js';
import type { AdminAuthService } from '../platform/auth.service.js';
import type { PartnerAccessService } from './partner-access.service.js';
import type { PartnerPayoutAccountService } from './partner-payout-account.service.js';
import { AppError } from '../../../shared/errors/app-error.js';
const id={type:'string',pattern:'^[a-fA-F0-9]{24}$'} as const;
const routes:FastifyPluginAsync<{service:PartnerPayoutAccountService;partnerAccessService:PartnerAccessService;adminAuthService:AdminAuthService}>=async(f,o)=>{
 const portal=createPartnerPortalAuthenticationHook(o.partnerAccessService),admin=createAdminAuthenticationHook(o.adminAuthService);
 f.post<{Body:{label:string;accountHolderName:string;bankName:string;ifscCode:string;accountLast4:string;accountVaultToken:string}}>('/me/payout-accounts',{preHandler:portal,schema:{body:{type:'object',additionalProperties:false,required:['label','accountHolderName','bankName','ifscCode','accountLast4','accountVaultToken'],properties:{label:{type:'string',minLength:1,maxLength:80},accountHolderName:{type:'string',minLength:2,maxLength:160},bankName:{type:'string',minLength:2,maxLength:160},ifscCode:{type:'string',pattern:'^[A-Za-z]{4}0[A-Za-z0-9]{6}$'},accountLast4:{type:'string',pattern:'^[0-9]{4}$'},accountVaultToken:{type:'string',pattern:'^vault_[A-Za-z0-9_-]{12,}$'}}}}},async(r,p)=>p.status(201).send(await o.service.create({partnerId:requirePartnerPortalContext(r).partnerId,...r.body})));
 f.get('/me/payout-accounts',{preHandler:portal},async r=>o.service.list(requirePartnerPortalContext(r).partnerId));
 f.post<{Params:{accountId:string}}>('/me/payout-accounts/:accountId/default',{preHandler:portal,schema:{params:{type:'object',required:['accountId'],properties:{accountId:id}}}},async r=>o.service.setDefault({partnerId:requirePartnerPortalContext(r).partnerId,accountId:r.params.accountId}));
 f.delete<{Params:{accountId:string};Querystring:{version:number}}>('/me/payout-accounts/:accountId',{preHandler:portal,schema:{params:{type:'object',required:['accountId'],properties:{accountId:id}},querystring:{type:'object',required:['version'],properties:{version:{type:'integer',minimum:1}}}}},async(r,p)=>{await o.service.disable({partnerId:requirePartnerPortalContext(r).partnerId,accountId:r.params.accountId,version:r.query.version});return p.status(204).send();});
 f.post<{Params:{accountId:string};Querystring:{version:number;documentType:string}}>('/me/payout-accounts/:accountId/documents',{preHandler:portal,schema:{params:{type:'object',required:['accountId'],properties:{accountId:id}},querystring:{type:'object',required:['version','documentType'],properties:{version:{type:'integer',minimum:1},documentType:{type:'string',minLength:2,maxLength:100}}}}},async(r,p)=>{const part=await r.file();if(!part)throw new AppError({code:'PARTNER_PAYOUT_DOCUMENT_REQUIRED',message:'A multipart document is required',statusCode:400});return p.status(201).send(await o.service.upload({partnerId:requirePartnerPortalContext(r).partnerId,accountId:r.params.accountId,...r.query,filename:part.filename,mimeType:part.mimetype,buffer:await part.toBuffer()}));});
 f.post<{Params:{partnerId:string;accountId:string};Body:{outcome:'VERIFIED'|'FAILED';failureReason?:string}}>('/admin/:partnerId/payout-accounts/:accountId/verify',{preHandler:admin,schema:{params:{type:'object',required:['partnerId','accountId'],properties:{partnerId:id,accountId:id}},body:{type:'object',additionalProperties:false,required:['outcome'],properties:{outcome:{enum:['VERIFIED','FAILED']},failureReason:{type:'string',minLength:1,maxLength:1000}}}}},async(r)=>o.service.verify({partnerId:r.params.partnerId,accountId:r.params.accountId,adminId:requireAdminRole(r).adminId,...r.body}));
}; export default routes;
